name: tfsec
description: tfsec action
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: 'Working Directory'
    required: false
    default: ""
  github_comment:
    description: 'Whether a comment is posted with github-comment'
    required: false
    default: 'false'
  ignore_hcl_errors:
    description: If true, tfsec's `--ignore-hcl-errors` is enabled
    required: false
    default: 'false'
runs:
  using: node20
  main: dist/index.js
